# Generated by Django 6.0.3 on 2026-04-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizada'), ('C', 'Cancelada')], default='P', max_length=1),
        ),
    ]
